### ISSUE TITLE
Prisma Cloud 503's

### ISSUE THREAD

**Issue by hoodsy** [graphcool/prisma-cloud-feedback#111]
Over the past few weeks I’ve been using Prisma Cloud. After experiencing a few intermittent outages (getting 503’s for all requests), I got some help from the always awesome @marktani, and I believed that I had resolved the issues.

Today, I am receiving the same 503 errors after not making any changes to my deployment for ~1 week. I’m unable to view data on app.prisma.sh, open the Prisma Playground, or complete any requests in my application.

**Comment by marktani** [comment]
Thanks a lot for bringing this up.

The first problems you mention were caused by a misconfiguration in your DB - increasing the connection limit resolved this.

We identified the second problem you mentioned as an issue with our auto scaling mechanism that occurred in rare cases and resolved the problem. We will make that part of auto scaling more robust soon as well.

Please refer to the chat from your Console or `support@graph.cool` if you need any further help with this :slightly_smiling_face:
