### ISSUE TITLE
Support database cluster with multiple instances

### ISSUE THREAD

**Issue by jhalvorson** [graphcool/prisma-cloud-feedback#89]
In certain cases it would be good to support a cluster of DBs with multiple instances instead of a single DB with both read and write perms, for example:

![prisma](https://user-images.githubusercontent.com/10282220/37164780-2d7f89ba-22f3-11e8-9f80-895480496123.jpg)

**Comment by marktani** [comment]
Thanks a lot, that's a great feature request 🙌

Currently, the cluster will log the following error message if you're connecting a DB setup as mentioned:

> The MySQL server is running with the --read-only option so it cannot execute this statement

**Comment by marktani** [comment]
So, it turns out that no change here is actually required.

Instead, when setting up a new Prisma cluster using Aurora, you need to make sure to use the "general" cluster endpoint, instead of a "specific" instance endpoint.

If you are running against a specific Aurora instance endpoint right now, please reach out to `support@prisma.io` to update the endpoint to the general cluster endpoint.
